# Generated by Django 6.1.1 on 2026-09-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmgmt', '0003_sprint_task_sprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('completed', 'Completed')], default='planned', max_length=15),
        ),
    ]
