# Generated by Django 6.1.1 on 2026-09-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmgmt', '0005_project_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='labels',
            field=models.CharField(blank=True, help_text='Comma-separated', max_length=200),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('task', 'Task'), ('bug', 'Bug'), ('story', 'Story')], default='task', max_length=10),
        ),
    ]
