# Generated by Django 6.1.1 on 2026-09-30 11:02

from django.db import migrations, models


def backfill_job_codes(apps, schema_editor):
    Job = apps.get_model('recruitment', 'Job')
    for job in Job.objects.filter(job_code='').order_by('pk'):
        job.job_code = f'JOB{job.pk:04d}'
        job.save(update_fields=['job_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_code',
            field=models.CharField(blank=True, editable=False, max_length=20, default=''),
            preserve_default=False,
        ),
        migrations.RunPython(backfill_job_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='job',
            name='job_code',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
