# Generated by Django 6.1.1 on 2026-09-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_job_job_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='resume',
        ),
        migrations.AddField(
            model_name='application',
            name='resume_content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='resume_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='resume_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
