# Generated by Django 6.1.1 on 2026-09-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, choices=[('development', 'Development'), ('designing', 'Designing'), ('hr', 'Hr'), ('sales', 'Sales'), ('other', 'Other')], max_length=20),
        ),
    ]
