# Generated by Django 6.1.1 on 2026-09-28 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_is_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_manager',
        ),
    ]
