# Generated by Django 6.1.1 on 2026-09-29 20:39

from django.db import migrations, models


def backfill_employee_codes(apps, schema_editor):
    Employee = apps.get_model('employees', 'Employee')
    for employee in Employee.objects.filter(employee_code='').order_by('pk'):
        employee.employee_code = f'EMP{employee.pk:04d}'
        employee.save(update_fields=['employee_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_leaverequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(blank=True, editable=False, max_length=20, default=''),
            preserve_default=False,
        ),
        migrations.RunPython(backfill_employee_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
